name: Vortex Matrix Run
on: workflow_dispatch

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3] # ৩টি মেশিন একসাথে চলবে

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute
        run: cargo run --release
